const cuisines = [
  { id: 1, name: "African" },
  { id: 2, name: "American" },
  { id: 3, name: "British" },
  { id: 4, name: "Cajun" },
  { id: 5, name: "Caribbean" },
  { id: 6, name: "Chinese" },
  { id: 7, name: "Eastern European" },
  { id: 8, name: "European" },
  { id: 9, name: "French" },
  { id: 10, name: "German" },
  { id: 11, name: "Greek" },
  { id: 12, name: "Indian" },
  { id: 13, name: "Irish" },
  { id: 14, name: "Italian" },
  { id: 15, name: "Japanese" },
  { id: 16, name: "Jewish" },
  { id: 17, name: "Korean" },
  { id: 18, name: "Latin American" },
  { id: 19, name: "Mediterranean" },
  { id: 20, name: "Mexican" },
  { id: 21, name: "Middle Eastern" },
  { id: 22, name: "Nordic" },
  { id: 23, name: "Southern" },
  { id: 24, name: "Spanish" },
  { id: 25, name: "Thai" },
  { id: 26, name: "Vietnamese" },
];

export default cuisines;
